### ISSUE TITLE
Question about column in database

### ISSUE THREAD

**Issue by muratunal** [faustbrian/Laravel-Voteable#3]
May you please explain what is the logic behind the _vote_id_ in database table? Is it because your planning more enhancement?

Cool stuff by the way, Thank u

Edit:
The reason i'm asking this question is this: In my project, there are some posts that are likely to be voted. But i have recieved Integrity Constraint Error on SQL. So i tend to alter the vote_id column to be nullable.

**Comment by anrus** [comment]
I have this error too!
